version: '3'

tasks:
  setup:
    desc: Init uv project here and baseline files in DIR
    requires:
      vars: [DIR]
    cmds:
      - |
          if [ ! -f "./pyproject.toml" ]; then
            uv init .
          fi
      - |
          if [ ! -f "{{.DIR}}/README.md" ]; then : > "{{.DIR}}/README.md"; fi
          if [ ! -f "{{.DIR}}/answer.py" ]; then : > "{{.DIR}}/answer.py"; fi
          if [ ! -f "{{.DIR}}/main.py" ]; then cp "{{.DIR}}/answer.py" "{{.DIR}}/main.py"; fi
          if [ ! -f "{{.DIR}}/test.py" ]; then cp "{{.DIR}}/answer.py" "{{.DIR}}/test.py"; fi
      - uv add --project . pytest ruff
      - uv sync --project .

  lint:
    desc: Run ruff on all subdirectories
    cmds:
      - |
          for d in */; do
            d="${d%/}"
            if [ "$d" = "__pycache__" ]; then
              continue
            fi
            if [ -d "$d" ]; then
              uv run --project . ruff check "$d"
            fi
          done

  test:
    desc: Run pytest with print output on DIR
    requires:
      vars: [DIR]
    cmds:
      - uv run --project . pytest -sv {{.DIR}}
